version: '2'

services:
    lampp:
        build:
            context: .
            dockerfile: dockerfile
        image: dch/lampp
        container_name: lampp
        network_mode: bridge
        volumes: 
            - ./www:/var/www/
            - ./data:/var/lib/mysql_data/
        hostname: lampp
        environment:
            - DB_NAME=test
            - DB_USER=user
            - DB_PASS=toto
        ports: 
            - 8080:80
        tty: true
