version: '2'

services:
    lampp:
        image: dvdche/lampp
        container_name: lampp
        network_mode: bridge
        volumes: 
            - ./www:/var/www/
            - ./data:/data/
        ports: 
            - 8080:80
        tty: true
